---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_zero
  chef_client_path: /usr/bin/chef-client
  require_chef_omnibus: 12.6.0

transport:
  name: sftp

platforms:
  - name: debian-7.9
    platform: debian
    driver_config:
      provision_command:
        - apt-get -y install build-essential

  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[simple-nexus-test]
    attributes:
      nexus:
        download_url: http://nexus.e3s.epam.com/content/repositories/e3s-install/nexus/2.13.0/nexus-2.13.0-01-bundle.tar.gz
        checksum: 4c4e88a2410e1740e688ea1ab3c6066a6a90f76c479e10e4718c517a27f3a614
        version: 2.13.0-01


